# SENSOR : ALIAS
#Conf file: /vendor/etc/thermal-engine.conf

[CPU-CLUSTER0-MONITOR]
algo_type           monitor
sampling            2000
sensor              cpuss-0
thresholds          75000        80000        85000
thresholds_clr      74000        79000        84000
actions             cpu-cluster0 cpu-cluster0 cpu-cluster0
action_info         1900800      1843200      1708800

[CPU-CLUSTER1-MONITOR]
algo_type           monitor
sampling            2000
sensor              cpuss-1
thresholds          75000        79000        83000        88000
thresholds_clr      73000        78000        81000        86000
actions             cpu-cluster1 cpu-cluster1 cpu-cluster1 cpu-cluster1
action_info         2188800      1920000      1708800      1497600

[CPU-CLUSTER2-MONITOR]
algo_type           monitor
sampling            2000
sensor              cpuss-1
thresholds          75000        79000        85000        88000
thresholds_clr      74000        78000        84000        87000
actions             cpu-cluster2 cpu-cluster2 cpu-cluster2 cpu-cluster2
action_info         2304000      1900800      1651200      1324800

[GPU-VIRTUAL-TEMP]
algo_type           virtual
trip_sensor         gpuss-0
sensors             gpuss-0 gpuss-1 gpuss-2 gpuss-3
sampling            2000
weights
math                2

[GPU-MONITOR]
algo_type           monitor
sampling            2000
sensor              GPU-VIRTUAL-TEMP
thresholds          65000      68000      72000     75000     79000     84000     85000
thresholds_clr      64000      66000      71000     74000     77000     82000     84000
actions             gpu        gpu        gpu       gpu       gpu       gpu       gpu
action_info         1100000000 1000000000 950000000 900000000 835000000 736000000 684000000
