# SENSOR : ALIAS
#Conf file: /vendor/etc/thermal-engine.conf

[CPU-CLUSTER0-MONITOR]
algo_type           monitor
sampling            2000
sensor              cpuss-0
thresholds          75000        80000        83000
thresholds_clr      74000        79000        81000
actions             cpu-cluster0 cpu-cluster0 cpu-cluster0
action_info         1900800      1843200      1708800

[CPU-CLUSTER1-MONITOR]
algo_type           monitor
sampling            2000
sensor              cpuss-1
thresholds          70000        73000        76000        82000        83000
thresholds_clr      69000        72000        75000        81000        82000
actions             cpu-cluster1 cpu-cluster1 cpu-cluster1 cpu-cluster1 cpu-cluster1
action_info         2611200      2188800      2073600      1920000      1708800

[CPU-CLUSTER2-MONITOR]
algo_type           monitor
sampling            2000
sensor              cpuss-1
thresholds          72000        74000        76000        80000        83000
thresholds_clr      71000        73000        75000        79000        81000
actions             cpu-cluster2 cpu-cluster2 cpu-cluster2 cpu-cluster2 cpu-cluster2
action_info         2668800      2304000      1900800      1766400      1651200
